name: free_beta
description: Elev8 route tracking app.
publish_to: "none"
version: 1.8.4+34

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_crashlytics: ^3.0.14
  firebase_storage: ^11.0.13
  flutter_riverpod: ^2.2.0
  image_picker: ^0.8.4+5
  intl: ^0.17.0
  path: ^1.8.0
  video_player: ^2.4.5
  auto_size_text: ^3.0.0
  firebase_messaging: ^14.2.6
  flutter_app_badger: ^1.5.0
  riverpod_annotation: ^2.0.2
  fl_chart: ^0.65.0
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  remove_from_coverage: ^2.0.0
  mocktail: ^0.3.0
  firebase_auth_mocks: ^0.13.0
  build_runner: ^2.3.3
  riverpod_generator: ^2.1.4
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
