// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmIXDb-B9lpRzafSsERKraWdCaWnHjmFc',
    appId: '1:342618963864:web:9f44b4063449d72766f5ed',
    messagingSenderId: '342618963864',
    projectId: 'free-beta',
    authDomain: 'free-beta.firebaseapp.com',
    storageBucket: 'free-beta.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs9TGyBpbVuWjnpU6xKHdHDDU5ibEOjg0',
    appId: '1:342618963864:android:1f7eb25738a376c266f5ed',
    messagingSenderId: '342618963864',
    projectId: 'free-beta',
    storageBucket: 'free-beta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR9TRuwZpgql2UKE9lbjqkSRZbhpIDHnY',
    appId: '1:342618963864:ios:9dca470f6bbeb72f66f5ed',
    messagingSenderId: '342618963864',
    projectId: 'free-beta',
    storageBucket: 'free-beta.appspot.com',
    iosClientId: '342618963864-rujmf7mj3dv12jsob2s0mf1bg279m0dh.apps.googleusercontent.com',
    iosBundleId: 'com.codej.freeBeta',
  );
}
