import 'package:free_beta/app/enums/enums.dart';
import 'package:free_beta/app/enums/route_rating.dart';
import 'package:free_beta/user/user_route_model.dart';

import 'models/route_model.dart';

class RouteRemoteDataProvider {
  Future<List<RouteModel>> getRoutes() async {
    return [
      RouteModel(
        routeKey: 1,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: true,
          isFavorited: false,
          rating: RouteRating.one,
          notes: 'too easy',
        ),
        location: Location.low,
        routeColor: RouteColor.black,
        section: Section.low1,
        climbType: ClimbType.boulder,
        difficulty: 'v0-v2',
      ),
      RouteModel(
        routeKey: 2,
        userRouteModel: UserRouteModel(
          isAttempted: false,
          isCompleted: false,
          isFavorited: false,
        ),
        location: Location.low,
        routeColor: RouteColor.yellow,
        section: Section.low1,
        climbType: ClimbType.boulder,
        difficulty: 'v4-v6',
      ),
      RouteModel(
        routeKey: 3,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: false,
          isFavorited: false,
        ),
        location: Location.low,
        routeColor: RouteColor.black,
        section: Section.low1,
        climbType: ClimbType.boulder,
        difficulty: 'v4-v6',
      ),
      RouteModel(
        routeKey: 4,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: true,
          isFavorited: true,
          rating: RouteRating.three,
          notes: 'campus life night',
        ),
        location: Location.low,
        routeColor: RouteColor.black,
        section: Section.low3,
        climbType: ClimbType.boulder,
        difficulty: 'v0-v2',
      ),
      RouteModel(
        routeKey: 5,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: true,
          isFavorited: false,
        ),
        location: Location.low,
        routeColor: RouteColor.seafoam,
        section: Section.low3,
        climbType: ClimbType.boulder,
        difficulty: 'v0-v2',
      ),
      RouteModel(
        routeKey: 6,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: true,
          isFavorited: false,
        ),
        location: Location.low,
        routeColor: RouteColor.blue,
        section: Section.low1,
        climbType: ClimbType.boulder,
        difficulty: 'v2-v4',
      ),
      RouteModel(
        routeKey: 7,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: true,
          isFavorited: false,
        ),
        location: Location.low,
        routeColor: RouteColor.pink,
        section: Section.low2,
        climbType: ClimbType.boulder,
        difficulty: 'v2-v4',
      ),
      RouteModel(
        routeKey: 8,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: true,
          isFavorited: false,
        ),
        location: Location.low,
        routeColor: RouteColor.pink,
        section: Section.low1,
        climbType: ClimbType.boulder,
        difficulty: 'v0-v2',
      ),
      RouteModel(
        routeKey: 9,
        userRouteModel: UserRouteModel(
          isAttempted: false,
          isCompleted: false,
          isFavorited: false,
          notes: 'A little too hard for right now',
        ),
        location: Location.low,
        routeColor: RouteColor.blue,
        section: Section.low3,
        climbType: ClimbType.boulder,
        difficulty: 'v4-v6',
      ),
      RouteModel(
        routeKey: 10,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: true,
          isFavorited: true,
          rating: RouteRating.three,
          notes: 'Just gotta send it',
        ),
        location: Location.high,
        routeColor: RouteColor.red,
        section: Section.high2,
        climbType: ClimbType.autoBelay,
        difficulty: 'Speed',
      ),
      RouteModel(
        routeKey: 11,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: false,
          isFavorited: false,
        ),
        location: Location.high,
        routeColor: RouteColor.seafoam,
        section: Section.high1,
        climbType: ClimbType.topRope,
        difficulty: '5.10',
      ),
      RouteModel(
        routeKey: 1,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: true,
          isFavorited: true,
          rating: RouteRating.two,
          notes: 'Go slow!',
        ),
        location: Location.mezzanine,
        routeColor: RouteColor.purple,
        section: Section.mezzanine1,
        climbType: ClimbType.autoBelay,
        difficulty: '5.10+',
      ),
      RouteModel(
        routeKey: 12,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: true,
          isFavorited: false,
        ),
        location: Location.high,
        routeColor: RouteColor.purple,
        section: Section.high2,
        climbType: ClimbType.autoBelay,
        difficulty: '5.8',
      ),
      RouteModel(
        routeKey: 13,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: true,
          isFavorited: false,
          rating: RouteRating.two,
        ),
        location: Location.high,
        routeColor: RouteColor.pink,
        section: Section.high2,
        climbType: ClimbType.topRope,
        difficulty: '5.8',
      ),
      RouteModel(
        routeKey: 14,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: true,
          isFavorited: false,
        ),
        location: Location.high,
        routeColor: RouteColor.green,
        section: Section.high2,
        climbType: ClimbType.topRope,
        difficulty: '5.9',
      ),
      RouteModel(
        routeKey: 15,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: true,
          isFavorited: true,
          notes: 'Go fast...',
        ),
        location: Location.high,
        routeColor: RouteColor.yellow,
        section: Section.high3,
        climbType: ClimbType.topRope,
        difficulty: '5.10',
      ),
      RouteModel(
        routeKey: 16,
        userRouteModel: UserRouteModel(
          isAttempted: true,
          isCompleted: false,
          isFavorited: false,
          rating: RouteRating.one,
        ),
        location: Location.low,
        routeColor: RouteColor.purple,
        section: Section.low4,
        climbType: ClimbType.boulder,
        difficulty: 'v2-v4',
      ),
    ];
  }
}
